### ISSUE TITLE
Which version of cuda is required for Drgnai?

### ISSUE THREAD

**Issue by abasle** [ml-struct-bio/drgnai#7]
Hello,

Our GPU cluster and installed software uses cuda 11.8.

I'm getting from drgnai pytest:
[...]
 FAILED testing/test_reconstruct.py::test_small_dataset_and_load[toy] - assert 15.355 == 14.415
FAILED testing/test_reconstruct.py::TestSetupIntegration::test_configuration_keys[hand_no-ind] - AssertionError: /conda/envs/drgnai-env/lib/python3.9/site-packages/torch/cuda/__init__.py:128: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL: h...
[...]

Which version of cuda is required for DrgnAI?
Cheers,
Arnaud

**Comment by michal-g** [comment]
Hey Arnaud,

The pytest suite for the package is meant to be run on a CPU (and we just added some text to the [docs](https://app.gitbook.com/o/gYlX75MBAfjzRuXIYbKH/s/mQzLIojwQvJKwWQnBP0u/getting-started) to clarify this!), and you may indeed get failing tests on a GPU for `test_reconstruct` which is testing here if reconstruction outputs match exactly. You can try again on a CPU to double-check — the CUDA warning is just nagging you that you could be using v12 on your cluster but it shouldn't affect DRGN-AI otherwise!

-Mike

**Comment by abasle** [comment]
Hi Michal,

Thanks! We will tyr DrgnAI a some challenging data with a lot of heterogeneity. 

Cheers,
Arnaud
